[versions]
agp = "8.11.1"
ksp = "2.2.0-2.0.2"
kotlin = "2.2.0"

kotlinDatetime = "0.7.1"
kotlinCoroutines = "1.10.2"
material = "1.12.0"
core = "1.17.0"
coreSplashscreen = "1.0.1"
appcompat = "1.7.1"
fragment = "1.8.9"
activityCompose = "1.10.1"
media = "1.7.1"
mediarouter = "1.8.1"
palette = "1.0.0"
preference = "1.2.1"
constraintlayout = "2.2.1"
swiperefreshlayout = "1.1.0"
recyclerview = "1.4.0"
cardview = "1.0.0"
viewpager = "1.1.0"
lifecycle = "2.9.3"
room = "2.7.2"
navigation = "2.9.3"
compose = "2025.08.01"

koin = "4.1.1"
coil = "3.3.0"
ktor = "3.2.3"
glide = "4.16.0"

markwon = "4.6.2"
m3color = "2025.4"
balloon = "1.6.13"
composeMarkdown = "0.5.7"
aboutlibraries = "13.0.0-b01"
fadingedgelayout = "1.0.0"
advrecyclerview = "1.0.0"
fastscroll = "1.3.0"
customactivityoncrash = "2.4.0"
keyboardvisibilityevent = "3.0.0-RC3"
taglib = "1.0.0-alpha25"
jaudiotagger = "2.3.15"
versioncompare = "1.5.0"

[libraries]
material-components = { module = "com.google.android.material:material", version.ref = "material" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-mediarouter = { module = "androidx.mediarouter:mediarouter", version.ref = "mediarouter" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-palette = { module = "androidx.palette:palette-ktx", version.ref = "palette" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version.ref = "viewpager" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinDatetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }

lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose" }

room = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

navigation-common = { module = "androidx.navigation:navigation-common-ktx", version.ref = "navigation" }
navigation-runtime = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigation" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
glide-okhttp3 = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }

markwon-core = { module = "io.noties.markwon:core", version.ref = "markwon" }
markwon-html = { module = "io.noties.markwon:html", version.ref = "markwon" }
markwon-glide = { module = "io.noties.markwon:image-glide", version.ref = "markwon" }
markwon-linkify = { module = "io.noties.markwon:linkify", version.ref = "markwon" }

m3color = { module = "com.github.Kyant0:m3color", version.ref = "m3color" }

balloon = { module = "com.github.skydoves:balloon", version.ref = "balloon" }
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "composeMarkdown" }
aboutlibraries = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibraries" }

fadingedgelayout = { module = "com.github.bosphere.android-fadingedgelayout:fadingedgelayout", version.ref = "fadingedgelayout" }
advrecyclerview = { module = "com.h6ah4i.android.widget.advrecyclerview:advrecyclerview", version.ref = "advrecyclerview" }
fastscroll = { module = "me.zhanghai.android.fastscroll:library", version.ref = "fastscroll" }

customactivityoncrash = { module = "cat.ereza:customactivityoncrash", version.ref = "customactivityoncrash" }
keyboardvisibilityevent = { module = "net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent", version.ref = "keyboardvisibilityevent" }

taglib = { module = "com.github.Kyant0:taglib", version.ref = "taglib" }
jaudiotagger = { module = "com.github.Adonai:jaudiotagger", version.ref = "jaudiotagger" }

versioncompare = { module = "io.github.g00fy2:versioncompare", version.ref = "versioncompare" }

[bundles]
kotlinx = ["kotlinx-datetime", "kotlinx-coroutines-core", "kotlinx-coroutines-android"]
lifecycle = ["lifecycle-common", "lifecycle-runtime", "lifecycle-livedata", "lifecycle-viewmodel", "lifecycle-viewmodel-compose"]
navigation = ["navigation-common", "navigation-runtime", "navigation-fragment", "navigation-ui"]
koin = ["koin-core", "koin-android", "koin-compose"]
coil = ["coil", "coil-compose", "coil-network"]
ktor = ["ktor-client-core", "ktor-client-okhttp", "ktor-serialization-json", "ktor-client-content-negotiation", "ktor-client-encoding"]
markwon = ["markwon-core", "markwon-glide", "markwon-html", "markwon-linkify"]

[plugins]
android = { id = "com.android.application", version.ref = "agp" }
android-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutlibraries" }